apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}
  labels:
    node: {{ .Values.app }}
spec:
  replicas: {{ .Values.replica.replicacount }}
  selector:
    matchLabels:
      node: {{ .Values.app }}
  template:
    metadata:
      labels:
        node: {{ .Values.app }}
    spec:
      imagePullSecrets:
      - name: dockercred
      volumes:
        - name: {{ .Values.volume.name }}
          secret:
            secretName: {{ .Values.volume.name }}
        - name: {{ .Values.volume.configname }}
          configMap:
            name: {{ .Values.volume.configname }}
        - name: kafka-ssl-config
          secret:
            secretName: fs-event-forwarder-kafka-ssl
      containers:
        - name: {{ .Values.app }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
{{- if .Values.resource.enabled }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- end }}
          volumeMounts:
          - name: {{ .Values.volume.name }}
            mountPath: {{ .Values.volume.mountPath }}
          - name: {{ .Values.volume.configname }}
            mountPath: {{ .Values.volume.mountPathConfig }}
          - name: kafka-ssl-config
            mountPath: /home/feeder-service
            readOnly: true
{{- if .Values.variables.enabled }} 
          env:
          - name: "FEEDER_SERVICE_PLATFORM"
            value: {{.Values.platform | quote}}
          - name: "KUBEARMOR_ENABLED"
            value: {{.Values.kubearmor.enabled | quote}}
            {{- range .Values.env }} 
          - name: {{ .name }} 
            value: "{{ .value }}"
          {{- end }}
{{- end }}  
