apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJhcnRpZmFjdG9yeS5hY2N1a25veC5jb20vcmVwb3NpdG9yeS9kb2NrZXItc25hcHNob3QiOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiS2xvdWRAXzEiLCJhdXRoIjoiWVdSdGFXNDZTMnh2ZFdSQVh6RT0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: dockercred
type: kubernetes.io/dockerconfigjson
